name: Android CI

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    environment: ${{ github.ref_name == 'main' && 'Production' || 'Preprod' }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Restaurer le keystore Android
      run: |
        echo "${ANDROID_KEYSTORE_BASE64}" | base64 --decode > android/app/activmotiv-release.keystore
        chmod 600 android/app/activmotiv-release.keystore
      env:
        ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

    - name: Restaurer google-services.json
      run: |
        echo "${GOOGLE_SERVICES_JSON_BASE64}" | base64 --decode > android/app/google-services.json
        chmod 600 android/app/google-services.json
      env:
        GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}

    - name: Grant execute permission for gradlew
      env:
        ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        EXPO_PUBLIC_API_URL: ${{ vars.EXPO_PUBLIC_API_URL }}
      run: |
        npm i
        cd ./android/
        chmod +x gradlew
        ./gradlew assembleRelease
        ./gradlew app:bundleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/release/app-release.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: android-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
